[project]
name = "fastapi-url-shortener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "redis[hiredis]>=6.1.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
]
